[package]
name = "fict-compiler-oxc"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true

[dependencies]
fict-diagnostics.workspace = true
fict-emit.workspace = true
fict-hir.workspace = true
fict-metadata.workspace = true
oxc.workspace = true
oxc_traverse.workspace = true

[dev-dependencies]
fict-reactivity.workspace = true
serde.workspace = true
serde_json.workspace = true
