// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

/// Compiler capability manifest schema version.
pub const COMPILER_CAPABILITY_MANIFEST_VERSION: u32 = 2;
/// Scope of the option claims recorded by the capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_SCOPE: &str = "certified-behavior-variant-options";
/// Package version whose behavior the capability manifest describes.
pub const COMPILER_CAPABILITY_PACKAGE_VERSION: &str = "0.35.0";
/// SHA-256 of the canonical compiler capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_DIGEST: &str = "sha256:8d85c68309d486fb1ac13747f35b2236f2893df69a1fae6f80edc065cb53c361";
