// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

/// Compiler capability manifest schema version.
pub const COMPILER_CAPABILITY_MANIFEST_VERSION: u32 = 2;
/// Scope of the option claims recorded by the capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_SCOPE: &str = "certified-behavior-variant-options";
/// Package version whose behavior the capability manifest describes.
pub const COMPILER_CAPABILITY_PACKAGE_VERSION: &str = "0.33.0";
/// SHA-256 of the canonical compiler capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_DIGEST: &str = "sha256:640aaf5a3566cc453604e92695f19e3c2acf266188fac94c1e388347eb1688c2";
