// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

/// Compiler capability manifest schema version.
pub const COMPILER_CAPABILITY_MANIFEST_VERSION: u32 = 2;
/// Scope of the option claims recorded by the capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_SCOPE: &str = "certified-behavior-variant-options";
/// Package version whose behavior the capability manifest describes.
pub const COMPILER_CAPABILITY_PACKAGE_VERSION: &str = "0.32.0";
/// SHA-256 of the canonical compiler capability manifest.
pub const COMPILER_CAPABILITY_MANIFEST_DIGEST: &str = "sha256:9335d7d9c51014704012110c5132765fa029b49ab0f6c7199b5debb331615689";
