// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

export const COMPILER_CAPABILITY_MANIFEST = {
  schemaVersion: 2,
  packageVersion: '0.34.0',
  backend: 'rust',
  scope: 'certified-behavior-variant-options',
  options: {
    dev: {
      default: false,
      supported: [false, true],
    },
    lazyConditional: {
      default: true,
      supported: [false, true],
    },
    getterCache: {
      default: true,
      supported: [false, true],
    },
    optimizeLevel: {
      default: 'safe',
      supported: ['safe', 'full'],
    },
    inlineDerivedMemos: {
      default: true,
      supported: [false, true],
    },
  },
} as const
export const COMPILER_CAPABILITY_MANIFEST_DIGEST =
  'sha256:7609a7cdf22a262d01beb8d67dbf8de6803b364bf49ee86e5744d24683df6de6'
