// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

export const COMPILER_CAPABILITY_MANIFEST = {
  schemaVersion: 2,
  packageVersion: '0.36.0',
  backend: 'rust',
  scope: 'certified-behavior-variant-options',
  options: {
    dev: {
      default: false,
      supported: [false, true],
    },
    lazyConditional: {
      default: true,
      supported: [false, true],
    },
    getterCache: {
      default: true,
      supported: [false, true],
    },
    optimizeLevel: {
      default: 'safe',
      supported: ['safe', 'full'],
    },
    inlineDerivedMemos: {
      default: true,
      supported: [false, true],
    },
  },
} as const
export const COMPILER_CAPABILITY_MANIFEST_DIGEST =
  'sha256:1fa42abc746d6c9dab2e6e68cfaecda5e0d0635abfee798b47598e5b1f623c84'
