// @generated by scripts/generate-compiler-capabilities.mjs; do not edit.

export const COMPILER_CAPABILITY_MANIFEST = {
  schemaVersion: 1,
  packageVersion: '0.32.0-next.0',
  backend: 'rust',
  options: {
    dev: {
      default: false,
      supported: [false, true],
    },
    lazyConditional: {
      default: true,
      supported: [false, true],
    },
    getterCache: {
      default: true,
      supported: [false, true],
    },
    optimizeLevel: {
      default: 'safe',
      supported: ['safe', 'full'],
    },
    inlineDerivedMemos: {
      default: true,
      supported: [false, true],
    },
  },
} as const
export const COMPILER_CAPABILITY_MANIFEST_DIGEST =
  'sha256:4599c258d302bef4fd707e150c8a4995279d46a430169ddfc1ebcfdf6bb74e68'
