// @generated by scripts/generate-metadata-protocol.mjs; do not edit.

/** Current module-reactivity metadata schema version. */
export const MODULE_REACTIVE_METADATA_VERSION = 1
/** Maximum recursive namespace depth accepted from a metadata snapshot. */
export const MAX_METADATA_NAMESPACE_DEPTH = 32
