// @generated by scripts/generate-metadata-protocol.mjs; do not edit.

/// Current module-reactivity metadata schema version.
pub const MODULE_REACTIVE_METADATA_VERSION: u32 = 1;
/// Maximum recursive namespace depth accepted from a metadata snapshot.
pub const MAX_METADATA_NAMESPACE_DEPTH: usize = 32;
