[package]
name = "fict-compiler"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true

[features]
default = []
preview = ["dep:fict-compiler-preview"]

[dependencies]
fict-compiler-oxc.workspace = true
fict-compiler-preview = { workspace = true, optional = true }
fict-diagnostics.workspace = true
fict-emit.workspace = true
fict-hir.workspace = true
fict-metadata.workspace = true
fict-reactivity.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
